sudo: required
language: php

notifications:
  email: false

php:
  - 7.0
  - 7.1

env:
  global:
    - TEST_PHP_ARGS="-q"
    - REPORT_EXIT_STATUS=1

before_script:
  - cd extension
  - phpize
  - ./configure
  - make -j4

script: make -f Makefile.local test_with_exit_status
